services:
  - type: web
    name: golpe-game
    env: node
    plan: free # Usa o plano gratuito para testar
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
